//! Cross-implementation parity: replay golden traces generated by the C#
//! `FanCurves.Core` (see `rust/parity-harness`) through the Rust port and
//! compare every output column. The traces are committed; regenerate them with
//! `dotnet run --project rust/parity-harness` after any intentional behaviour
//! change in the C# core.

use fan_core::{CurvePoint, FanCurve, IdleKick, ResponseFilter, StopProbe};

/// Both sides compute in f64 with the same operation order, so outputs should
/// be bit-identical; the epsilon only absorbs printf/parse round-trips.
const EPS: f64 = 1e-9;

fn parse(line: &str) -> Vec<Option<f64>> {
    line.split(',')
        .map(|c| if c.is_empty() { None } else { Some(c.parse::<f64>().expect(c)) })
        .collect()
}

fn close(a: f64, b: f64) -> bool {
    (a - b).abs() <= EPS
}

fn quiet_cpu() -> Vec<CurvePoint> {
    let p = CurvePoint::new;
    vec![
        p(20.0, 0.0), p(50.0, 10.0), p(55.0, 20.0), p(62.0, 40.0), p(70.0, 50.0),
        p(76.0, 65.0), p(84.0, 81.0), p(88.0, 90.0), p(92.0, 100.0),
    ]
}

fn quiet_case() -> Vec<CurvePoint> {
    let p = CurvePoint::new;
    vec![
        p(20.0, 0.0), p(40.0, 5.0), p(42.0, 10.0), p(60.0, 20.0),
        p(70.0, 40.0), p(75.0, 60.0), p(82.0, 82.0), p(86.0, 100.0),
    ]
}

fn perf_cpu() -> Vec<CurvePoint> {
    let p = CurvePoint::new;
    vec![p(20.0, 45.0), p(50.0, 60.0), p(65.0, 75.0), p(80.0, 90.0), p(90.0, 100.0)]
}

/// (averaging, hysteresis, hold, slew up, slew down, zero snap)
fn make_filter(cfg: (f64, f64, f64, f64, f64, f64)) -> ResponseFilter {
    let mut f = ResponseFilter::new();
    f.averaging_seconds = cfg.0;
    f.hysteresis_c = cfg.1;
    f.step_down_hold_seconds = cfg.2;
    f.slew_up_percent_per_sec = cfg.3;
    f.slew_down_percent_per_sec = cfg.4;
    f.zero_snap_percent = cfg.5;
    f
}

/// Columns: now,temp,applynow,out,target,curve_level,pending,remaining,hyst,snapped
fn replay_filter(csv: &str, mut filter: ResponseFilter, points: &[CurvePoint], name: &str) {
    let curve = FanCurve::new(points);
    for (i, line) in csv.lines().skip(1).enumerate() {
        let c = parse(line);
        let (now, temp) = (c[0].unwrap(), c[1].unwrap());
        if c[2].unwrap() != 0.0 {
            filter.apply_now();
        }
        let out = filter.step(now, temp, &curve);
        let row = |msg: &str| format!("{name} row {i} (t={now:.2}): {msg}");

        assert!(close(out, c[3].unwrap()), "{}", row(&format!("out {out} != {}", c[3].unwrap())));
        assert!(
            close(filter.target_level(), c[4].unwrap()),
            "{}",
            row(&format!("target {} != {}", filter.target_level(), c[4].unwrap()))
        );
        assert!(
            close(filter.curve_level, c[5].unwrap()),
            "{}",
            row(&format!("curve_level {} != {}", filter.curve_level, c[5].unwrap()))
        );
        match (filter.pending_down_level, c[6]) {
            (Some(a), Some(b)) => assert!(close(a, b), "{}", row(&format!("pending {a} != {b}"))),
            (None, None) => {}
            (a, b) => panic!("{}", row(&format!("pending {a:?} != {b:?}"))),
        }
        match (filter.down_hold_remaining, c[7]) {
            (Some(a), Some(b)) => assert!(close(a, b), "{}", row(&format!("remaining {a} != {b}"))),
            (None, None) => {}
            (a, b) => panic!("{}", row(&format!("remaining {a:?} != {b:?}"))),
        }
        assert_eq!(filter.hysteresis_holding, c[8].unwrap() != 0.0, "{}", row("hysteresis_holding"));
        assert_eq!(filter.snapped_to_zero, c[9].unwrap() != 0.0, "{}", row("snapped_to_zero"));
    }
}

#[test]
fn filter_matches_csharp_quiet_cpu() {
    replay_filter(
        include_str!("golden/filter-quiet-cpu.csv"),
        make_filter((90.0, 1.5, 25.0, 9.0, 8.0, 20.0)),
        &quiet_cpu(),
        "filter-quiet-cpu",
    );
}

#[test]
fn filter_matches_csharp_case_with_zero_snap() {
    replay_filter(
        include_str!("golden/filter-case-snap.csv"),
        make_filter((25.0, 4.0, 10.0, 7.0, 7.0, 20.0)),
        &quiet_case(),
        "filter-case-snap",
    );
}

#[test]
fn filter_matches_csharp_apply_now() {
    replay_filter(
        include_str!("golden/filter-applynow.csv"),
        make_filter((20.0, 3.0, 10.0, 8.0, 8.0, 0.0)),
        &quiet_cpu(),
        "filter-applynow",
    );
}

#[test]
fn probe_matches_csharp() {
    // Columns: now,temp,demand,out,holding
    let mut probe = StopProbe::new();
    probe.run_seconds = 30.0;
    probe.probe_seconds = 30.0;
    probe.stable_range_c = 3.5;
    probe.fail_retry_seconds = 60.0;
    probe.max_temp_c = 78.0;
    for (i, line) in include_str!("golden/probe.csv").lines().skip(1).enumerate() {
        let c = parse(line);
        let (now, temp, demand) = (c[0].unwrap(), c[1].unwrap(), c[2].unwrap());
        let out = probe.step(now, temp, demand);
        assert!(close(out, c[3].unwrap()), "probe row {i} (t={now:.2}): out {out} != {}", c[3].unwrap());
        assert_eq!(probe.holding(), c[4].unwrap() != 0.0, "probe row {i} (t={now:.2}): holding");
    }
}

#[test]
fn kick_matches_csharp() {
    // Columns: now,demand,out,kicking
    let mut kick = IdleKick::new();
    kick.stopped_seconds = 10.0;
    kick.kick_percent = 5.0;
    kick.kick_seconds = 5.0;
    for (i, line) in include_str!("golden/kick.csv").lines().skip(1).enumerate() {
        let c = parse(line);
        let (now, demand) = (c[0].unwrap(), c[1].unwrap());
        let out = kick.step(now, demand);
        assert!(close(out, c[2].unwrap()), "kick row {i} (t={now:.2}): out {out} != {}", c[2].unwrap());
        assert_eq!(kick.kicking(), c[3].unwrap() != 0.0, "kick row {i} (t={now:.2}): kicking");
    }
}

#[test]
fn curve_eval_matches_csharp() {
    // Columns: temp,quiet,perf,single,empty
    let quiet = FanCurve::new(&quiet_cpu());
    let perf = FanCurve::new(&perf_cpu());
    let single = FanCurve::new(&[CurvePoint::new(60.0, 33.0)]);
    let empty = FanCurve::new(&[]);
    for (i, line) in include_str!("golden/curve-eval.csv").lines().skip(1).enumerate() {
        let c = parse(line);
        let t = c[0].unwrap();
        for (curve, col, name) in
            [(&quiet, 1, "quiet"), (&perf, 2, "perf"), (&single, 3, "single"), (&empty, 4, "empty")]
        {
            let v = curve.evaluate(t);
            assert!(close(v, c[col].unwrap()), "curve row {i} {name}({t}) = {v} != {}", c[col].unwrap());
        }
    }
}
